version: '3.8'

services:
  registry:
    build:
      context: .
      dockerfile: parent/registry/boot/Dockerfile.runtime
    container_name: registry_local
    hostname: registry
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=LOCAL
      - REGISTRY_ENDPOINT=http://registry:8080/registry
      - REDIS_ADDRESS=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"

